# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.0
language: objective-c

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
  - DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=11.4'
  - DESTINATION='platform=iOS Simulator,name=iPhone XS,OS=12.4'
  - DESTINATION='platform=iOS Simulator,name=iPhone 11,OS=13.7'
  - DESTINATION='platform=iOS Simulator,name=iPhone 11,OS=14.0'


script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TableViewLiaison.xcworkspace -scheme TableViewLiaison-Example -destination "$DESTINATION" | xcpretty
