# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6S,OS=9.3'
  - DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
  - DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=11.4'
  - DESTINATION='platform=iOS Simulator,name=iPhone XS,OS=12.2'

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TableViewLiaison.xcworkspace -scheme TableViewLiaison-Example -destination "$DESTINATION" | xcpretty
